moveit_controller_manager: moveit_fake_controller_manager/MoveItFakeControllerManager

moveit_fake_controller_manager:
  controller_names:
    - ur_manipulator_controller
    - gripper_controller

  ur_manipulator_controller:
    type: fake
    default: true
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

  gripper_controller:
    type: fake
    default: true
    joints:
      - gripper_gripper_joint
      - gripper_right_finger_joint